load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "find_median",
    srcs = ["find_median.cc"],
    hdrs = ["find_median.h"],
    visibility = ["//src/main:__pkg__", "//test:__pkg__"]
)
