cc_test (
    name = "test",
    srcs = [
        "find_median_utest.cc",
    ],
    deps = [
        "//src/lib:find_median",
        "@googletest//:gtest",
        "@googletest//:gtest_main" # Only if find_median_utest.cc has no main()
    ],
)